services:
  db:
    restart: always
    image: postgres:alpine3.19
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_db
    volumes:
      - "./migrations/000001_tables.up.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge